version: '3' 

services:
    
  web: 
    build: ./docker-config/php
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    depends_on:
      - mysql

  nginx:
    image: nginx
    build: ./docker-config/nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/src
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  mysql:
    image: mysql:8.0
    ports:
      - 3386:3306
    environment:
      MYSQL_DATABASE: yt_dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yt_user
      MYSQL_PASSWORD: yt_user
      TZ: 'Asia/Tokyo'
      
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql
      # - ./docker-config/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker-config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    depends_on:
      - mysql-volume

  mysql-volume:
    image: busybox
    volumes:
      - ./docker-config/mysql:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #     - PMA_PASSWORD=root
  #   links:
  #     - mysql
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /sessions